[build]

command = "npm run production"
publish = "build_production"

[build.environment]

PHP_VERSION = "7.2"

redirects = [
  {from = "/blog", to = "/articles"},
  {from = "/about", to = "/"},
  {from = "/problem-with-vuejs-devtools-extension/", to = "/blog/problem-with-vuejs-devtools-extension/},
  {from = "/doctype/", to = "/blog/what-does-a-doctype-do/"} ,
  {from = "/archives/", to = "/articles"},
  {from = "/services", to = "/my-work"} 
]