[build]

command = "npm run production"
publish = "build_production"

[build.environment]

PHP_VERSION = "7.2"

# Redirects from what the browser requests to what we serve

/about                                          /
/blog                                           /articles
/services                                       /my-work
/problem-with-vuejs-devtools-extension/         /blog/problem-with-vuejs-devtools-extension
/doctype/                                       /blog/what-does-a-doctype-do/
/archives/                                      /articles