[build]

command = "npm run production"
publish = "build_production"

[build.environment]

PHP_VERSION = "7.2"

[[redirects]]
  from = "/blog"
  to = "/articles"

[[redirects]]
  from = "/about"
  to = "/"

[[redirects]]
  from = "/services"
  to = "/my-work"

[[redirects]]
  from = "/archives"
  to = "/articles"

[[redirects]]
  from = "/problem-with-vuejs-devtools-extension"
  to = "/blog/problem-with-vuejs-devtools-extension"

[[redirects]]
  from = "/doctype"
  to = "/blog/what-does-a-doctype-do/"