[build]

command = "npm run production"
publish = "build_production"

[build.environment]

PHP_VERSION = "7.2"

[[redirects]]
  from = "/blog"
  to = "/articles"

[[redirects]]
  from = "/about"
  to = "/"